### ISSUE TITLE
Social icons hard to see in GitHub Dark Theme

### ISSUE THREAD

**Issue by vikasganiga05** [keshavsingh4522/keshavsingh4522#32]
The social icons are hard to see in GitHub's Dark Theme. My suggestion is to use colored icons instead of black social icons.

#### Screenshot

![image](https://user-images.githubusercontent.com/74750414/118695551-f3999d00-b82a-11eb-90b1-b10ca1e349d7.png)

**Comment by keshavsingh4522** [comment]
thanks for this, I will use colored icons in place of this.
